### PR TITLE
Cuda9

### PR DESCRIPTION
**Pull request by eruditej**
I get more megahashes with glide stride!

### CODE REVIEW

**Comment by KlausT** [comment]
It's actually a little bit slower on my 1070.
Maybe 1% or so

**Comment by hannarong** [comment]
Based on Christian Buchner's &amp; Christian H.'s CUDA project
based on the Fork by tpruvot@github with X14,X15,X17,WHIRL,Blake256 and LYRA2 support , and some others, check the [README.txt](README.txt)
Reforked and optimized by sp-hash@github and KlausT@github 

* KlausT:
    BTC 1QDwdLPrPYSoPqS7pB2kGG84YX6hEcQ4JN
    BCH 1AH1u7B4KtDTUBgmT6NrXyahNEgTac3fL7
* sp-hash:
    BTC donation address: 1CTiNJyoUmbdMRACtteRWXhGqtSETYd6Vd
* tpruvot:
    BTC donation address: 1AJdfCpLWPNoAMDfHF1wD5y8VgKSSTHxPo

A part of the recent algos were originally written by [djm34](https://github.com/djm34).

This variant was tested and built with Visual Studio 2015 on Windows 10

## About source code dependencies

This project requires some libraries to be built :
* OpenSSL (prebuilt for win)
* Curl (prebuilt for win)
* pthreads (prebuilt for win)

This fork now contains these libraries for both x86 and x64 platforms (windows).

**Comment by shyang7526** [comment]
💙

**Comment by platinum4** [comment]
Close this pull request; it's not relevant anymore since now on CUDA 10

**Pull request closed without merging**
